### ISSUE TITLE
Add class to timeline-events when sender is the logged-in user

### ISSUE THREAD

**Issue by tcpipuk** [tulir/gomuks#537]
I'm looking for a class to be added to timeline events when the sender is the currently logged-in user, with the objective to help custom CSS treat them differently to other events.

I've been able to pick out non-`div.same-sender` events using `div.timeline-event:has(.sender-avatar[data-target-user="@+:tomfos.tr"])` but this isn't very portable, and I can't see a way to include `div.same-sender` without them being flagged somehow:

```css
div.timeline-event:has(.sender-avatar[data-target-user="@+:tomfos.tr"]) {
    justify-self: end;

    >div.sender-avatar {
        grid-area: sender;
        justify-self: end;
    }

    >div.event-sender-and-time {
        justify-self: end;
        margin-right: 1em;
    }

    >div.event-content {
        justify-self: end;
        margin-right: -7px;
        overflow: hidden;
        width: 100%;

        div.message-text {
            justify-self: end;
        }

        >blockquote.reply-body {
            border-left: none;
            border-right: 2px solid;
            justify-self: end;
            max-width: 100%;

            >div.reply-sender {
                justify-self: end;
                max-width: 60%;
            }
        }
    }
}
```

**Comment by tcpipuk** [comment]
Thanks for adding the `own-event` class! For anyone following, this is how I'm using it now:

```css
div.timeline-event.own-event {
    justify-self: end;

    >div.sender-avatar {
        grid-area: sender;
        justify-self: end;
    }

    >div.event-sender-and-time {
        justify-self: end;
        margin-right: 1em;
    }

    >div.event-content {
        justify-self: end;
        margin-right: -7px;
        overflow: hidden;
        width: 100%;

        div.media-container, div.message-text {
            justify-self: end;
        }

        >blockquote.reply-body {
            border-left: none;
            border-right: 2px solid;
            justify-self: end;
            max-width: 100%;

            >div.reply-sender {
                justify-self: end;
                max-width: 60%;
            }
        }
    }
}
```
