### ISSUE TITLE
Notification count overflow

### ISSUE THREAD

**Issue by sumnerevans** [tulir/gomuks#540]
I know that Tulir never sees an unread count > 1, but us mere mortals do fairly regularly. 2 digits is fine, but once it gets to 3, it overflows the circle.

![image](https://github.com/user-attachments/assets/633457ee-42b9-4f93-880d-fd13c3a134d9)

We should probably do something like https://getbootstrap.com/docs/5.0/components/badge/#pill-badges to allow for larger numbers.

**Comment by JadedBlueEyes** [comment]
My particular solution to this:

```css
div.room-entry {
    &>div.room-entry-unreads {
        &>div.unread-count {
            border-radius: 1rem;
            width: unset;
            min-width: calc(1rem - 1rem/4);
            padding: calc(1rem/8) calc(1rem/4);
        }
    }
}
```

I've added more horizontal padding than vertical to avoid letters touching on the corner (border-radius makes it smaller), and then the min-width has to account for the uneven padding to keep the default state square.

![image](https://github.com/user-attachments/assets/d4995fe2-577b-49cf-a9e1-b58af7e041cc)

Only problem is it'd probably overflow the default style once it reaches 4 digits 😓
